name: Web App CD Pipeline
on:
  workflow_run:
    workflows: ['.NET CI Pipeline']
    types: [completed]
    branches: [main]
env:
  PROJECT_NAME: Simple_Insurance_portal
  ARTIFACT_NAME: Simple_Insurance_portal-drop
  ENVIRONMENT: dev
jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Download ${{ env.ARTIFACT_NAME }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.PROJECT_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        package: artifacts/